/* eslint-disable react/no-unescaped-entities */
import React, { Fragment } from 'react'
import { compose, setDisplayName } from 'recompose'
import { Card, CardHeader, CardBody } from 'reactstrap'
import { withRouteData } from 'react-static'
import Header from 'Site/components/Header'
import Footer from 'Site/components/Footer'
import withTracker from 'Site/components/withTracker'

export default compose(
  setDisplayName('Terms'),
  withTracker,
  withRouteData
)(({ translations }) => (
  <>
    <Header translations={translations} />
    <div className='container my-4'>
      <Card>
        <CardHeader className='font-weight-bold'>
          <h4>Terms of Use</h4>
        </CardHeader>
        <CardBody className='text-muted'>
          <div>
            <div>
              <h5 className='font-weight-bold'>Terms</h5>
              <p>By accessing the website at https://faa.st, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law. Faast is held by Faast Limited (2036919), a company incorporated in British Virgin Islands and having its registered address at Quijano Chambers, P.O. Box 5159, Road Town, Tortola, British Virgin Islands (hereinafter “Faast”)</p>
              <p className='font-weight-bold'>The risk of loss in trading or holding cryptocurrency can be substantial. You should therefore carefully consider whether trading or holding cryptocurrency is suitable for you in light of your financial condition.</p>
              <p>Updated: May 2020</p>
              <h5 className='font-weight-bold'>DEFINITIONS</h5>
              <p><b>Faast Network - </b>a non-custodial peer-to-peer software platform which provides a marketplace for two individuals, to conduct peer to peer cryptocurrency trades from their own cryptocurrency wallets </p>
              <p><b>Maker -</b> an individual who registers on the Faast Network to enable another individual to sell one cryptocurrency for another cryptocurrency. This individual is engaging in such activity on an infrequent basis and not specifically for profit or gain.</p>
              <p><b>Taker - </b> an individual who buys one Cryptocurrency from another individual (the Maker) using a Wallet;</p>
              <p><b>Parties – </b> both the Maker and the Taker;</p>
              <p><b>Channel Address - </b> a P2SH Cryptocurrency multi-signature address, which requires two keys (one belongs to the Maker, one to the Faast Network) to sign the Cryptocurrency transaction.</p>
              <p><b>Offer – </b>the availability sell one cryptocurrency for another, published by a Maker on the Faast Network. An Offer indicates the respective Maker’s intention to accept one cryptocurrency in exchange for another Cryptocurrency;</p>
              <p><b>Purchase Contract – </b>Cryptocurrency sell/purchase contract concluded between the Maker and the Taker who has accepted Makers created Offer. Terms of Trade specified within the respective Offer creation process become the rules of the Purchase Contract;</p>
              <p><b>Payment window - </b> timeframe within which the offer between the Maker and the Taker shall be completed (i.e. Cryptocurrency shall be received by the Maker and the payment shall be received by the Taker). Payment window is defined by the Maker in the Offer creation process;</p>
              <p><b>Wallet – </b>a wallet that operates on the a Blockchain Network;</p>

              <h5 className='font-weight-bold'>Use License</h5>
              <p>Permission is granted to temporarily download one copy of the materials (information or software) on Faast website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not: modify or copy the materials; use the materials for any commercial purpose, or for any public display (commercial or non-commercial); attempt to decompile or reverse engineer any software contained on the Faast website; remove any copyright or other proprietary notations from the materials; or transfer the materials to another person or "mirror" the materials on any other server. This license shall automatically terminate if you violate any of these restrictions and may be terminated by Faast at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.</p>

              <h5 className='font-weight-bold'>Lost Passwords</h5>
              <p>WARNING: In many cases, a lost of forgotten password can result in the inability to transfer cryptocurrency!</p>

              <p>Faast does not store passwords. IF YOU LOSE YOUR PASSWORD, YOU MAY LOSE ALL ACCESS TO YOUR cryptocurrency.</p>

              <h5 className='font-weight-bold'>ELIGIBILITY</h5>
              <p>By accessing or using the Site, you represent and warrant that you are at least 18 years old and have not previously been suspended or removed from the Site. You also represent and warrant that you are not a resident of a Restricted Location as listed below. The list of Restricted States is subject to change at any time.</p>

              <p>RESTRICTED LOCATIONS: NORTH KOREA, IRAN, CUBA, UNITED STATES, SUDAN, UNITED KINGDOM, CRIMEA</p>

              <h5 className='font-weight-bold'>Third Parties</h5>
              <p>Faast has no control over, or liability for, the delivery, quality, safety, legality or any other aspect of any goods or services that you may purchase or sell to or from a third party. Faast is not responsible for ensuring that a buyer or a seller you may transact with will actually complete the transaction or is authorized to do so. If you experience a problem with any goods or services purchased from, or sold to, a third party in connection with cryptocurrency transferred using the Faast services, or if you have a dispute with such third party, you must resolve the dispute directly with that third party.</p>

              <h5 className='font-weight-bold'>Cryptocurrency Protocols</h5>
              <p>Faast does not own or control the underlying software protocols which govern the operation of Digital Currencies supported on our platform. In general, the underlying protocols are open source and anyone can use, copy, modify, and distribute them. By using Faast, you acknowledge and agree (i) that Faast is not responsible for operation of the underlying protocols and that Faast makes no guarantee of their functionality, security, or availability; and (ii) that the underlying protocols are subject to sudden changes in operating rules (a/k/a “forks”), and that such forks may materially affect the value, function, and/or even the name of the cryptocurrency . In the event of a fork, you agree that Faast may temporarily suspend Faast operations (with or without advance notice to you) and that Faast may, in its sole discretion, decide whether or not to support (or cease supporting) either branch of the forked protocol entirely. You acknowledge and agree that Faast assumes absolutely no responsibility whatsoever in respect of an unsupported branch of a forked protocol.</p>

              <h5 className='font-weight-bold'>Marketplace</h5>
              <p>Eligible users in certain jurisdictions may use the Faast network to conduct peer-to-peer trades of one cryptocurrency for another cryptocurrency. Faast is not a counterparty to these conversions.  Fas.st provides a marketplace to facilitate the purchase and sale of cryptocurrency. Payments are exchanged on a peer-to-peer basis between the Makers in the Faast Network and Takers in the Faast Network. Faast provides an API or "Application Program Interface" which provides cryptocurrency addresses which are generally used to convert from one cryptocurrency to another. These cryptocurrency addresses belong to Makers on the faast network. Faast takes no responsibility if a conversion does not complete as expected. Any disputes should be directed to the owner of the associated cryptocurrency address. The conversions are subject to the "conversion rate" for the given transaction, which are derived from offers posted by makers on the faast networks. "Conversion rate" means the price of a given supported Cryptocurrency amount as quoted in offers made by Maker’s and submitted to the Faast API, which may be displayed on the Faast website. The conversion rate is stated as a "Price" or as a "Rate," which is the price in terms of cryptocurrency at which you may convert a supported cryptocurrency on a cryptocurrency network. You acknowledge that the price conversion rate may not be exactly as stated on the Faast website. You agree, as a condition of using any Faast Services, to accept the conversion rate as the sole conversion metric. Faast reserves the right to delay any conversion Service transaction if it perceives a risk of fraud or illegal activity. Faast does not guarantee the availability of its Service, and the act of converting supported cryptocurrency does not result in a guarantee that you may convert your supported cryptocurrency again at a later time.</p>

              <p>You cannot cancel, reverse, or change any transaction marked as complete or pending. If Faast suspects the transaction involves (or has a high risk of involvement in) money laundering, terrorist financing, fraud, or any other type of financial crime; in response to a subpoena, court order, or other government order; if Faast reasonably suspects that the transaction is erroneous; or if Faast suspects the transaction relates to Prohibited Use or a Prohibited Business as set forth below. In such instances, Faast will reverse the transaction and we are under no obligation to allow you to reinstate a purchase or sale order at the same price or on the same terms as the cancelled transaction.</p>

              <h5 className='font-weight-bold'>Terms Specific to Maker Network Participants</h5>
              <p>The Faast Network may charge a Maker an API network access fee for continued access to the Faast Network. This fee is subject to change at any time, without notice. This fee is published via the Faast API and is available in real time before Offers are assigned on the Faast Network marketplace. Faast may collect API network access fees in accordance with agreements with downstream affiliates, which are included in said API network access fees. Network access fees vary depending on several factors including, but not limited to: the number of Makers on the Faast Network, if specific Offers are filled through a referral, the size and frequency of completed offers, and the blockchain network fees at the time of an offer. The Faast Network also requires Makers to maintain cryptocurrency in a Channel Address. The cryptocurrency in the Channel Address may be withdrawn by the maker on request, given that there are no active, or in progress offers on the Faast Network from the Maker. Faast may ensure quality of service though use of the provisions of “Dispute Resolution” outlined below.</p>
              <h5 className='font-weight-bold'>Dispute Resolution</h5>
              <p>If an Offer is determined to not have completed within the Payment Window, or if the Taker and the Maker are in a disagreement over an Offer, a dispute will be triggered by the Faast network, either automatically, or on request of one of the Parties. If and when they are allowed to do so by these Terms of Services, Disputes may be resolved by Faast support staff, or through an automated resolution system on the Faast network.
Faast may take the Takers side if any, but not limited to, of the following criteria have been met:
              </p>
              <ul>
                <li>The Maker has not broadcasted a payment within the Payment Window;</li>
                <li>The Maker is no longer communicating with the Faast Network API;</li>
                <li>The Maker has broadcasted a payment for an incorrect amount.</li>
              </ul>

              <p>Which will lead to the following result: the Faast Network will and sign a transaction in which Cryptocurrency shall be transferred from the Payment Channel Address to the Taker.
Faast may take the Takers side, when any, but not limited to, of the following criteria have been met:
              </p>
              <ul>
                <li>A third party has frozen/stopped/held the payment made by Taker;</li>
                <li>Payment was not made by the Taker, or only a partial payment was made;</li>
                <li>A cryptocurrency network is experiencing a degradation of service wherein payment or delivery of cryptocurrency is not possible within the Payment Window</li>
              </ul>

              <h5 className='font-weight-bold'>Provisions specific to the Affiliate program</h5>
              <p>Hereinafter, the Faast Affiliate Program is called “Program” for short, and you, the affiliate, will be called “Affiliate” and the takers you refer will be called “Affiliate Taker”. Once you begin using the “Program”, you must be fully compliant with the Terms and Services to remain eligible for the Program.
You can begin using the “Program” pending account approval. If an Affiliate Taker has completed an Offer with a Maker on the Faast network, you may be eligible to an Affiliate Reward, based on certain conditions.
In order to be compensated, you request an Affiliate Payout via the Faast API, or Faast Affiliate Portal. Affiliate Rewards are subject to review to ensure these terms and conditions have been met. Pending affiliate payouts should not be considered guaranteed, and are subject to the provisions in this agreement.
When referring an Affiliate Taker, you will also be able to specify a specific Affiliate Rate you expect to receive in return for the referral. The maker who executes the Offer with the Affiliate Taker will take into account this Affiliate Rate when creating the Offer. If the Maker is successful in automated hedging of the offer, the full Affiliate Rate will be recorded as payable to the Affiliate. If the Maker is unable to properly hedge the offer, then an Affiliate Reward will be calculated based on the maximum possible amount without the Maker taking a loss on the offer.
If the Maker fails to remit Affiliate Rewards to the Faast network, the Maker will be removed from the Network, but outstanding Affiliate Rewards will not be honored.
Upon termination of the Program and/or any portion thereof, for any reason, or upon disqualification, termination, suspension of a Affiliate account for any reason, Affiliate ceases to receive Affiliate Rewards from any Offers, that his Affiliate Taker may complete hereinafter.
Faast reserves the right to immediately terminate any Affiliation or deny use of our API if:
              </p>
              <ol>
                <li>An Affiliate does not adequately integrate the Faast API into their service;</li>
                <li>An Affiliate engages in activity that Faast determines, in its sole discretion, to be against the collaborative spirit of the Program; or</li>
                <li>An Affiliate or its Takers fails to comply with the then-current general Terms of Service</li>
              </ol>
              <p>Additionally, Faast reserves the right to terminate any Taker or Affiliate’s use of the Service at any time for any reason or no reason, in Faast sole discretion.  Additionally, Faast may, without prior notice, suspend the Service, change the Service; stop providing the Service or features of the Service, to any Affiliate or to Taker generally; or create usage or Transaction limits for the Service. Faast may permanently or temporarily terminate or suspend Affiliate access to the Service without notice and liability for any reason, including if in our sole determination Affiliate violates any provision of these Terms, or Faast may: (a) suspend, restrict, or terminate Affiliate access to any or all of the Services, and/or (b) deactivate or cancel an Affiliate if: (i) we are so required by a facially valid subpoena, court order, or binding order of a government authority; (ii) we reasonably suspect Affiliate of using the Service in connection with a Prohibited Activity; (iii) use of an Affiliate is subject to any pending litigation, investigation, or government proceeding and/or perceived heightened risk of legal or regulatory non-compliance associated with Affiliate or Affiliate Taker activity; (iv) Affiliate takes any action that Faast deems as circumventing Faast’s controls; (v) Faast decides, in its sole discretion, to suspend or terminate Affiliate access to the Service for any reason or no reason.
Upon termination for any reason or no reason, Affiliate continues to be bound by these Terms. Affiliate is solely responsible for its interactions with other Parties on the Faast Network. Faast reserves the right, but has no obligation, to monitor disputes between Affiliate Takers and Makers. You acknowledge that Faast’s decision to take certain actions, including limiting access to, suspending, or terminating an Affiliate, may be based on confidential criteria. You agree that Faast is under no obligation to disclose the details of its risk management, or security procedures to you.
5. Indemnity Affiliate agrees to defend, indemnify and hold harmless Faast and its subsidiaries, agents, licensors, managers, and other affiliated companies, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising from: (a) Affiliate’s use of and access to the Service, including any data or content transmitted or received by Affiliate; (b) Affiliate’s violation of any term of these Terms; (c) Affiliate’s violation of any third-party right, including without limitation any right of privacy or Intellectual Property Rights; (d) Affiliate’s violation of any applicable law, rule or regulation; or (e) Affiliate’s willful misconduct.
              </p>

              <h5 className='font-weight-bold'>Prohibited Use</h5>
              <p><b>When accessing or using the Services, you agree that you will use the Services in accordance with the terms and conditions in this Agreement (including the Privacy Policy) and not commit any unlawful act, and that you are solely responsible for your conduct while using the Services. Without limiting the generality of the foregoing, you agree that you will not:
Use the Services in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying the Services, or that could damage, disable, overburden or impair the functioning of the Services in any manner; engage in any activity which could violate, or assist in violation of, any law, statute, ordinance, or regulation, sanctions programs administered in the countries where we conduct business or operations, or which would involve proceeds of any unlawful activity; publish, distribute or disseminate any unlawful material or information; interfere with another user’s access to or use of any of the Services; defame, abuse, extort, harass, stalk, threaten or otherwise violate or infringe the legal rights (such as, but not limited to, rights of privacy, publicity and intellectual property) of other users; incite, threaten, facilitate, promote, or encourage hate, racial intolerance, or violent acts against others; harvest or otherwise collect information from our Website about other users; engage in any activity which operates to defraud, defame or otherwise cause any damage to Faast or our users; or provide any false, inaccurate, deceptive or misleading information to Faast or to another user in connection with the Services or as otherwise provided or requested pursuant to this Agreement; introduce to the Services any virus, Trojan, worms, logic bombs or other harmful material; use any robot, spider, crawler, scraper or other automated means or interface not provided by us to access the Services or to extract data; attempt to circumvent any content filtering techniques we employ, or attempt to access any service or area of the Services that you are not authorized to access; engage in transactions involving items that infringe or violate any copyright, trademark, right of publicity or privacy or any other proprietary right under the law, or other licensed materials without the appropriate authorization from the rights holder; use of Faast intellectual property, name, or logo, including use of Faast’s trade or service marks, without prior written consent from us or in a manner that otherwise harms Faast or the Faast brand; any action that implies an untrue endorsement by or affiliation with Faast; or develop any third-party applications that interact with the Services without our prior written consent; or encourage or induce any third party to engage in any of the activities prohibited under this.
              </b>
              </p>

              <h5 className='font-weight-bold'>Disclaimer</h5>
              <p>The materials on the Faast website are provided on an 'as is' basis. Faast makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Faast does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.</p>

              <h5 className='font-weight-bold'>Limitation of Liability</h5>
              <p>IN NO EVENT SHALL Faast, ITS AFFILIATES AND SERVICE PROVIDERS, OR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, AGENTS, JOINT VENTURERS, EMPLOYEES OR REPRESENTATIVES, BE LIABLE (A) FOR ANY LOST PROFITS OR ANY SPECIAL, INCIDENTAL, INDIRECT, INTANGIBLE, OR CONSEQUENTIAL DAMAGES, WHETHER BASED IN CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE, ARISING OUT OF OR IN CONNECTION WITH AUTHORIZED OR UNAUTHORIZED USE OF THE Faast SITE OR THE Faast SERVICES, OR THIS AGREEMENT, EVEN IF AN AUTHORIZED REPRESENTATIVE OF Faast HAS BEEN ADVISED OF OR KNEW OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. THIS MEANS, BY WAY OF EXAMPLE ONLY (AND WITHOUT LIMITING THE SCOPE OF THE PRECEDING SENTENCE), THAT IF YOU CLAIM THAT Faast FAILED TO PROCESS A BUY OR SELL TRANSACTION PROPERLY, YOUR DAMAGES ARE LIMITED TO NO MORE THAN THE VALUE OF THE SUPPORTED cryptocurrency AT ISSUE IN THE TRANSACTION, AND THAT YOU MAY NOT RECOVER FOR LOST PROFITS, LOST BUSINESS OPPORTUNITES, OR OTHER TYPES OF SPECIAL, INCIDENTIAL, INDIRECT, INTANGIBLE, OR CONSEQUENTIAL DAMAGES IN EXCESS OF THE VALUE OF THE SUPPORTED cryptocurrency AT ISSUE IN THE TRANSACTION.SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.THE Faast SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT ANY REPRESENTATION OR WARRANTY, WHETHER EXPRESS, IMPLIED OR STATUTORY.TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, Faast SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND/OR NON-INFRINGEMENT. Faast DOES NOT MAKE ANY REPRESENTATIONS OR WARRANTIES THAT ACCESS TO THE SITE, ANY PART OF THE Faast SERVICES, OR ANY OF THE MATERIALS CONTAINED THEREIN, WILL BE CONTINUOUS, UNINTERRUPTED, TIMELY, OR ERROR-FREE.</p>

              <p>In no event shall Faast or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on the Faast website, even if Faast or a Faast authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.</p>

              <h5 className='font-weight-bold'>Arbitration</h5>
              <p>PLEASE READ THIS SECTION CAREFULLY – IT MAY SIGNIFICANTLY AFFECT YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT AND TO HAVE A JURY HEAR YOUR CLAIMS.</p>

              <p>To expedite and control the cost of disputes, you and we agree that any legal or equitable claim arising out of or relating to your use of the Services or these Terms, including the formation, validity, enforceability, scope, or applicability of these Terms, will be resolved as follows: except for claims for injunctive or equitable relief or claims regarding intellectual property rights (which may be brought in any competent court without the posting of a bond), any dispute arising under your use of the Services shall be finally settled on an individual basis through confidential, binding arbitration in accordance with the British Virgin Islands International Arbitration Centre's rules for arbitration of consumer-related disputes, available at www.bviiac.org, and you and Faast hereby expressly waive trial by jury. This means that all claims other than intellectual property lawsuits, such as copyright or trademark infringement lawsuits, or claims seeking non-monetary relief would be subject to binding arbitration. This includes claims which may pre-date this agreement. The arbitration shall take place in the British Virgin Islands, in the English language and the arbitral decision may be enforced in any court. At your request, hearings may be conducted in person or by telephone and the arbitrator may provide for submitting and determining motions on briefs, without oral hearings. Payment of all filing, administration and arbitrator fees will be governed by the BVIIAC' rules. The prevailing party in any action or proceeding to enforce this agreement shall be entitled to costs and attorneys' fees. To begin an arbitration proceeding, you must send a letter by e-mail to legal@faa.st.</p>

              <p>ADDITIONALLY, YOU HEREBY WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION. We each agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated or representative action. If for any reason a claim proceeds in court rather than in arbitration, we each waive any right to a jury trial. If a court or federal regulator with oversight over Faast decides that applicable law precludes enforcement of any of this section’s limitations as to a particular claim for relief, then that claim (and only that claim) must be severed from the arbitration and may be brought in court, subject to your and Faast's right to appeal the court's decision. All other claims will be arbitrated.</p>

              <h5 className='font-weight-bold'>Accuracy of materials</h5>
              <p>The materials appearing on the Faast website could include technical, typographical, or photographic errors. Faast does not warrant that any of the materials on its website are accurate, complete or current. Faast may make changes to the materials contained on its website at any time without notice. However Faast does not make any commitment to update the materials.</p>

              <h5 className='font-weight-bold'>General Provisions</h5>
              <p>Entire Agreement: This Agreement, and the Privacy Policy by reference herein comprise the entire understanding and agreement between you and Faast as to the subject matter hereof, and supersedes any and all prior discussions, agreements and understandings of any kind (including without limitation any prior versions of this Agreement), and every nature between and among you and Faast. Section headings in this Agreement are for convenience only, and shall not govern the meaning or interpretation of any provision of this Agreement.</p>

              <p>Assignment: You may not assign any rights and/or licenses granted under this Agreement. We reserve the right to assign our rights without restriction, including without limitation to any Faast affiliates or subsidiaries, or to any successor in interest of any business associated with the Faast Services. Any attempted transfer or assignment in violation hereof shall be null and void. Subject to the foregoing, this Agreement will bind and inure to the benefit of the parties, their successors and permitted assigns.</p>

              <p>Severability: If any provision of this Agreement shall be determined to be invalid or unenforceable under any rule, law or regulation or any governmental agency, local, provincial, or federal, such provision will be changed and interpreted to accomplish the objectives of the provision to the greatest extent possible under any applicable law and the validity or enforceability of any other provision of this Agreement shall not be affected.</p>

              <p>Change of Control: In the event that Faast is acquired by or merged with a third party entity, we reserve the right, in any of these circumstances, to transfer or assign the information we have collected from you as part of such merger, acquisition, sale, or other change of control.</p>

              <p>Survival: All provisions of this Agreement which by their nature extend beyond the expiration or termination of this Agreement, including, without limitation, sections pertaining to suspension or termination, Faast Account cancellation, debts owed to Faast, general use of the Faast Site, disputes with Faast, and general provisions, shall survive the termination or expiration of this Agreement.</p>

              <p>Force Majeure: We shall not be liable for delays, failure in performance or interruption of service which result directly or indirectly from any cause or condition beyond our reasonable control, including but not limited to, any delay or failure due to any act of God, act of civil or military authorities, act of terrorists, civil disturbance, war, strike or other labor dispute, fire, interruption in telecommunications or Internet services or network provider services, failure of equipment and/or software, other catastrophe or any other occurrence which is beyond our reasonable control and shall not affect the validity and enforceability of any remaining provisions.</p>

              <h5 className='font-weight-bold'>Links</h5>
              <p>Faast has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Faast of the site. Use of any such linked website is at the user's own risk.</p>

              <h5 className='font-weight-bold'>Modifications</h5>
              <p>Faast may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.</p>

              <h5 className='font-weight-bold'>Governing Law</h5>
              <p>These terms and conditions are governed by and construed in accordance with the laws of the British Virgin Island and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.</p>

            </div>
          </div>
        </CardBody>
      </Card>
    </div>
    <Footer translations={translations} />
  </>
))
